-- Items rarity table for absolvementEsp
-- Edit this file on GitHub to add/update items
-- Loaded remotely by esp.lua via dx9.Get()

local ITEM_RARITY = {}
local function reg(tier, items)
    for _, v in ipairs(items) do ITEM_RARITY[v] = tier end
end


reg("Void", {
    "Void Essence",
})

reg("Relic", {
    "Aranae Eye","Gelidium Slime","Kix'xm Branch","Feriun Horns","Calvar Skull",
    "Facadae Wraps","Katiyr Claws","Cragg Rock","Voidtouched Necklace","Raging Demon",
    "Oni Mask","Sacred Rose","Lightning Charm","Mana Orb","Iron Counterweight",
    "Gumption Amulet","Amorian Sigil","Artifact of Chaos","Bloodsage Vial","Bloodsage Pact",
    "Winterspeaker's Amulet","Winter Mittens","Antidote","Grounding Rod","Rosary",
    "Lucky Dice","Cryptstalker Medallion","Ember Rune","Tome of Tranquility",
    "Shifting Sands Hourglass","Swordbreaker","Suspicious Grimoire","Metal Arm",
    "Artifact of Greed","Artifact of Wrath","Artifact of Slaughtering","Artifact of Chance",
    "Artifact of Judgement","Artifact of Sloth","Artifact of Pride","Artifact of Desertion",
    "Artifact of Gluttony","Vanguard's Aegis","Zephyr Amulet","Thorns of Discord",
    "Abyssal Charm","Mark of Retribution","Tidal Crest","Fading Light Token","Runic Shard",
    "Stormcaller's Eye","Warden's Brace","Emberheart Stone","Umbral Mirage","Stalwart Crest",
    "Serpent's Fang","Windsprint Charm","Gilded Touch","Dewdrop Prism",
})

reg("Mythical", {
    "Blindside","Worshipper's Spear","Warlord","Subzero Temperatures","Self-Conductor",
    "Sealed Sword","Rune of Protection","Regeneration","Recuperate","Positive Reinforcement",
    "Cataclysmic Fragmentation","Phoenix Incarnate","Patient Three","Overheat",
    "One's Inner Eye","Rotbomb","King's Treasury","Justicar Greatsword","Hellfire",
    "Headtaker's Greatsword","Gravetender's Scythe","Gambler's Mix","Frostwake Spear",
    "Soulbind","Feather Dancer","Ethereal Kris","Strangulation","Hand of Justice",
    "Telemancy","Bloodletter's Katana","Chain Pull","Arcane Gateway","Everwinter",
    "Soul Burst","Innervate","Fuselighter","Cryopathic Eruption","Plague Detonation",
    "Mass Enfeeblement","Repurposed Strength","Sudden Death","Venomous Suppression",
    "Arcane Arrow","Epidemic","Ash Tornado","Necropolis","Electric Barrage",
    "Stonebleeder Greataxe","Flaming Tempest","Army of the Dead","Black Mold","Martyr",
    "DarkBrickBossSkill1","DarkBrickBossSkill2","DarkBrickBossSkill3","DarkBrickBossSkill4",
    "DarkBrickBossSkill5","DarkBrickBossSkill6","Spellslinger's Serum",
    "Arcane Resonance Potion","Elemental Bypass","Soulslag","Marshwalker","Followup",
    "Absolvement","Bless","Biofrost","Detonation Switch","Soul Siphon","Dragonmaw Pike",
    "Rotspike","Flamelash","Floral Rapier","Drowned Scythe","Stormweaver","Renew",
    "Ascendant Arcane Crystal","Ascendant Disease Crystal","Ascendant Earth Crystal",
    "Ascendant Fire Crystal","Ascendant Frost Crystal","Ascendant Holy Crystal",
    "Ascendant Lightn","Ascendant Nature Crystal","Ascendant Physical Crystal",
    "Ascendant Shadow Crystal","Ascendant Water Crystal","Ascendant Wind Crystal",
    "Gaea's Wrath","Crystal Mirror",
    "FrostwakeBossSkill1","FrostwakeBossSkill2","FrostwakeBossSkill3","FrostwakeBossSkill4",
    "FrostwakeBossSkill5","FrostwakeBossSkill6","FrostwakeBossSkill7",
    "BloodsageBossSkill1","BloodsageBossSkill2","BloodsageBossSkill3","BloodsageBossSkill4",
    "BloodsageBossSkill5","BloodsageBossSkill6",
    "Tidebreaker Cutlass","Quietus","Desecrate","Divine Plume Scythe","Silkwing Bow",
    "Cinderheart Maul","Final Rites Greataxe","Supersonic","Mimicry","Viscosity","Pact",
    "Zephyr Fang Glaive","Keen Reflexes","Apocalypse","Rejuvenation","Miasma","Regicide",
    "Broadside","Blooming Seed","Nature's Embrace","Crystallized Katana","Charge",
    "Black Ice Ravager Axe","Silken Snare","Methods of Magic","Kick Up",
    "Methods of Magic - Fire","Methods of Magic - Water","Methods of Magic - Earth",
    "Methods of Magic - Frost","Methods of Magic - Disease","Methods of Magic - Holy",
    "Methods of Magic - Physical","Methods of Magic - Nature","Methods of Magic - Wind",
    "Methods of Magic - Lightning","Methods of Magic - Shadow",
    "Suffocation","Uproot","Ground Bullet","Frozen Dry Pierce","Disembowelling Grapple",
    "Mana Armor","Aegis Plating","Final Stand","Good Times","Mana Juggle",
    "Mastery of Defense","Mysterious Attractor","Victory Celebration","Dyspnea",
    "Twisted Narrative","Paranoia","Scorching Sandscreen",
})

reg("Unique", {
    "Life Unbound","Nerves of Steel","Iron Spike","Glutton's Delight","Noble's Stash",
    "Volley","Ignition","Frozen Uppercut","Vagabond's Katana","Tanto","Guillotine Axe",
    "Gilded Greatsword","Gilded Longsword","Gilded Rapier","Gilded Shortsword","Soft Spot",
    "Shifting Sands","Gilded Bow","Mending Elixir","Flashspark Vial","Blood Plague","Rally",
    "War Banner","Necrotic Rot","Recovery","Pulse","Obsidian Obelisk","Cauterized Flesh",
    "Inner Peace","Reverberating Slash","Frostbite","Double Stomp",
    "Fatal Strike","Pyromania","Knight's Longsword","Moonshade Scythe","Betrayer's Longsword",
    "Double Tap","Briarlash","Giantslayer","Flood","Quicksand","Rapture","Transcendence",
    "Improved Ambush","Extinguisher","False Prophet","Keen Eye","Unbridled Rage",
    "Sanguine Infusion","Needles and Pins","Slaughtering Ire","Stabilizers","Fearful Approach",
    "Fire in a Bottle","Wind Crush","Whirling Flames","Rapid Fire","Eternal Frost",
    "Celestial Rain","Umbral Pin","Night Slash","Froststeel Glaive","Sundawn Maul",
    "Wind Vortex","Hydrolance","Shredding Gale","Phylactery","Titan's Strike Fists","Cleave",
    "Arrow Rain","Beartrap","Spring Loaded","Shock Sweep","Radiant Light","Whirlpool",
    "Shoulder Slam","Frost Femur Breaker","Hypoxia","Deep Chill","Air Trap","Backwash",
    "Dawnglory","Crusader","Convulse","Frozen Shatter","Festering Ghoul",
    "Execution Sentence","Long Arm of the Law","Lightning Rod","Lightning Link","Rotter",
    "Never-Ending Tempest","Unholy Stitching","Stay of Execution","Concussive Slam",
    "Crushing Smite","Anguishing Cry","Potion of Treasure Seeking","Active Ampoule",
    "Grandbriar","Vinewrap","Reap","Stalker","Rust","Permafrost Slam","Flamespout",
    "Tempest's Wrath","Endless Tempest","Abyssal Grasp","Shadowflame Eruption",
    "Primal Arcane Crystal","Primal Disease Crystal","Primal Earth Crystal",
    "Primal Fire Crystal","Primal Frost Crystal","Primal Holy Crystal",
    "Primal Lightning Crystal","Primal Nature Crystal","Primal Physical Crystal",
    "Primal Shadow Crystal","Primal Water Crystal","Primal Wind Crystal",
    "Preserve","Obsidian Particulate","Strike While Hot","Rumbling Halt",
    "Thundering Grasp","Thunderclap","Steelshade Spear","Mass Hysteria","Haunt",
    "Colder Mist","Strengthened Rot","Palm Strike","Davy Jones' Locker","Lung Collapse",
    "Spore Spew","Wraith","Rotshade Bolt","Holy Wrath","Frozen Expungement","Ad Mortum",
    "Seasonal Empowerment: Summer","Seasonal Empowerment: Winter","Holy Flame Charge",
    "Chain Gang","Plasma Line","Acrobatics","Death Absorption","Elemental Leech",
    "Intimidation","Mana Stabilization","Refund","Reinforced Plating","Well Fed","Bastion",
    "Mana Leech","Shockwave","Child of Earth","Overstimulation","Manic Storm","Deluge",
    "Diligent Defender","Heatstroke","Orespray","Bracing Impact","Safety Net",
    "Elemental Bandages","Fearmongering","Gilded Eclipse Bulwark","Gilded Heater Shield",
    "Gilded Ivory Tower Shield",
})

reg("Rare", {
    "Mending","Garrote Vil","Iron Sharpening Stone","Vitality","Iron Soul",
    "Terrifying Presence","Smoke Powder","Squire's Satchel","Enlightenment","Pyre","Rush",
    "Frost Nova","Iron Shortsword","Iron Longsword","Iron Greatsword","Iron Greataxe",
    "Iron Axe","Rage Vial","Peppermint Extract","Stoneskin Potion","Fire Blast","Dust Storm",
    "I.O.U.","Vampirism","Rappelling","Bodkin Point","Bolstering Shout","Posthaste",
    "Cry of Heroism","Firestarter","Wildfire","Speed Demon","Plan A","Plan B","Panic Button",
    "Kindling","Napalm","Sacred Field","Smoldering Embers","Zen Energy","Mutilate",
    "Frozen Fist","Earthquake","Deep Freeze","Song of Storms","Bamboo Katana","Hoplite Spear",
    "Serrated Knife","Chronic Plague","Instigator","Firm Stance","Electrolysis","ESP",
    "Windreaver","Like Iron","Encroaching Vines","Flame Smash","Execute","Fetid Strike",
    "Ironbark","Titan's Force","Flame-Bathe","Flashspark Powder","Suffocate","Sand Expansion",
    "Icy Leftover","Everlasting Echo","Twin Mirage","Razor's Bite","Chameleon's Brew",
    "Smoke Bomb","Rebound","Walk In Shadows","Stealth","Reflection","Focus Shot",
    "Pressure Jet","Endless Mire","Subzero Slam","Winter's Fury","Contagious Venom",
    "Unhoned Arcane Shard","Greater Umbra","Greater Smolders","Greater Snowfall",
    "Greater Rainfall","Greater Mudslide","Greater Mold Spores","Greater Gust",
    "Greater Friction","Greater Censer","Greater Sprout","Greater Tempered Metal",
    "Arcana Absorption","Hot Hands","Ironthorn Rapier","Ironclad Maul","Slicing Winds",
    "Geyser","Curse of Stone","Void Dagger","Shock Grenade","Crumbling Wall","Terraforming",
    "Concrete","Slate","Grounding","Hydropush","Starfall Aegis","Ironleaf Bulwark",
    "Nightsong Ward","Iron Hand Fists","Bombardment","Gore","Nitroglycerine","Anulled Murmur",
    "Ambush","Enfeeble","Steel Beartrap","Judgement","Shackle","Null","Pestilence",
    "Crashing Wave","Chain Lightning","Vortex","Chain Current","Eternal Radiance","Emptiness",
    "Darksteel Wraps","Nothing","Dream Eater","Paralysis","Oppressive Binding","Arcing Arrows",
    "Rushing Waters","Rip Current","Quick Charge","Waterspout","Void","Alchemist's Fire",
    "Liquid Iron","Bloodstone Ichor","Daylily Extract","Essence of Dusk","Bottled Tornado",
    "Enchanted Dew","Sample 19-1-06","Electrolytes","Holy Water","Tenacity Tonic",
    "Crown of Thorns","Genesis","Swifter Strides","Dragonfruit","Pomegranate","Warm Winter",
    "Blood Frenzy","Weak Point","Light in the Dark","Shatter","Resonant Wind Crystal",
    "Crystalline Eruption","Bloodbath","Stoneskin","Cataclysm",
    "Resonant Arcane Crystal","Resonant Disease Crystal","Resonant Earth Crystal",
    "Resonant Fire Crystal","Resonant Frost Crystal","Resonant Holy Crystal",
    "Resonant Lightning Crystal","Resonant Nature Crystal","Resonant Physical Crystal",
    "Resonant Shadow Crystal","Resonant Water Crystal",
    "Condemn","Sacred Slash","Molten Core","Hasty Winds","Combative Winds","Warforged Glaive",
    "Accelerated Rot","Rotbind","Synapse","Defibrillation","Lingering Scare","Aquapop",
    "Neutralism","Symbiotic Relationship","Symbiosis","Seasonal Empowerment: Spring",
    "Entropic Convergence","Glacial Rot","Righteous Fury","Persecution","Zeal","Double-Palm",
    "Damaged Hull","Abyss","Crushing Depths","Strong Jaws","Venomous Stings","Altering Spores",
    "Sporeblossom","Kingsbane","Serial Kingslayer","Strengthened Void","Shadow Dancer",
    "Mind-Crumbling Infestation","Piercing Psyche","Aquatic Upheaval","Riptide","Solarsulk",
    "Sun God's Domain","Open Circuit","Static Orb","Cold Breath","Chastise","Expungement",
    "Befoulment","Scorching Rune Detonation","Gunpowder Barrel","Seasonal Empowerment: Fall",
    "Bloody Mass","White Flame Blast","Greater Pyre","Greater Enfeeble","Flame Ring",
    "Intracellular","Righteous Conjecture","Colossal Might","Pneumonia","Cryopreservation",
    "Pressure","Gaia Fist","Air Jet","Bargain","Negotiation","Hunt","Counter Art","Focus",
    "Physical Exertion","Reaping Blow","Pressure Jump","Decayed Consumption","Gangrene",
    "Metal Plating","Glancing Blows","Peacekeeper","Drizzle","Ripple",
})

reg("Uncommon", {
    "Swift Strides","Vigor","Healing Waters","Copper Sharpening Stone","Makeshift Bomb",
    "Mango","Peasant Pouch","Ice Blades","Pierce","Tendon Slice","Whirling Blades",
    "Bronze Shortsword","Bronze Longsword","Strong Back","Suspicious Tincture","Thunderstrike",
    "Icicle Eruption","Deep Wound","Defrost","Puncture","Deep Cut","Aggressive Stance",
    "Chilling Presence","Hunting Dagger","Stone Wall","Fervid Infection","Fortitude",
    "Carbon Monoxide","Jolt","Achilles Tendon","Negative Reaction","Seasonal Shift: Summer",
    "Fiery Annihilation","Stone Skull","Acute Suffering","Second Degree","Darkfern Scythe",
    "Bronze Heater Shield","Bronze Kite Shield","Bronze Targe","Insulation","Echolocation",
    "Agitator","Envenom","Holy Mirror","Root Burst","Black Death","Burning Judgement",
    "Chlorophyll","Broad Arrow","Everlasting Quiver","Honed Pierce","Scattering Arcs",
    "Expel Light","Kiwi","Dense Flora","Righteous Flames","Rootball","Steelbark",
    "Weeping Roots","Serrated Arrow","Vine Extension","Warming Brew","Sinking Depths",
    "Lingering Weakness","Corrosive Touch","Unhoned Arcane Fragment","Umbra","Smolders",
    "Snowfall","Rainfall","Mudslide","Mold Spores","Gust","Friction","Censer","Sprout",
    "Tempered Metal","Clashing Mana","Stonegrip Fists","Earth Headbutt","Chargepulse",
    "Rough Waters","Abyssal Lunacy","Null Agony","Granite","Electrocution","Magnetic Pulse",
    "Agonising Shout","Arcs","Accelerated Heat","Quickshot","Explosive Arrow","Stone Spike",
    "Chain Rattle","Shadowstep","Staggering Push","Chillblains","Lightning Reflexes",
    "Hurricane","Permafrost","Pandemic","Wind Crack","Tsunami","Sorrowful Ties","Slow Strides",
    "Bronze Greatsword","Cat's Eye Concoction","Pineapple","Darkness","Evasive Killer",
    "Cryocompaction","Glacial Melt","Icequake","Infection","Splash","Rabid Slash",
    "Extensive Winds","Polished Bark Bow","Bloom",
    "Faint Arcane Crystal","Faint Disease Crystal","Faint Earth Crystal","Faint Fire Crystal",
    "Faint Frost Crystal","Faint Holy Crystal","Faint Lightning Crystal","Faint Nature Crystal",
    "Faint Physical Crystal","Faint Shadow Crystal","Faint Water Crystal","Faint Wind Crystal",
    "Crusading Strike","Acid Rain","Cleansing Rain","Gale Freedom","Stoneman","Rock Gash",
    "Gouging Slice","Arterial Tear","Dullfang Katana","Iron-Tipped Spear","Ironbark Axe",
    "Reinforced Glaive","Steelbreaker Greataxe","Stonebreaker Maul","Short Out",
    "Neptunic Puddle","Trident Throw","Concentrated Matter","Diseased Mist",
    "Spread of Contamination","Cherubim","Apotheosis","Seraphim","Flaming Persecution",
    "Smitten Balance","Tiger Palm","Compression","Crushing Stomp","Reckless Leap",
    "Hornet Swarm","Swarm","Spore Surf","Pilfer","Banshee","Clashing Rot","Surging Tides",
    "Muscle Spasm","Core Shock","Electrogravitate","Cold Front","Smite","Soul Shackle",
    "Dynamite Fuse","Seasonal Shift: Winter","Seasonal Shift: Fall","Seasonal Shift: Spring",
    "Famine","Sorrow","Gravel","Preservation","Bartering","Updraft","Disorient","Choreography",
    "Sweet Symphony","Persist","Devil's Pact","To Take and Give","Surprise Attack","Relief",
    "Methods of Defense","Hands Up","Cracked Windpipe","Hymn Knowledge: Harmonia","Firewall",
    "Frozen Soul","Barbed Ice Harpoon","Cold Start","Icicle Detonation","Meteorite",
    "Chainmail","Paladin","Gladiator","Reinforced Bracing","Custodian","Lurker",
    "Aqua Prison","Chase",
})

reg("Common", {
    "Wooden Shield","Discard (Holy DMG)","Lesser Sprout","Lucky Coin","Poison Arrow","Pear",
    "Wind Blast","Whetstone","Static Shock","Reverse Slice","Copper Greatsword",
    "Copper Longsword","Copper Shortsword","Lesser Heal","Thermal Shock","Whiplash","Apple",
    "Discard (Armor)","Discard (Weapon DMG)","Discard (HP)","Cardio","Lesser Gust",
    "Lesser Snowfall","Lesser Mold Spores","Lesser Rainfall","Lesser Tempered Metal",
    "Lesser Umbra","Proper Footing","Lesser Smolders","Lesser Friction","Lesser Mudslide",
    "Discard (Wind DMG)","Discard (Fire DMG)","Discard (Frost DMG)","Distract","Berserking",
    "Deep Laceration","Fevergash","Discard (Disease DMG)","Discard (Water DMG)","Troublemaker",
    "Polar Caps","Warmonger","Charred Armor","Seismic Stomp","Frozen Copier","Wide Arc",
    "Ice Slam","First Degree","Rime Stab","Detection","Onion","Barbed Teeth","Orange",
    "Wind Cannon","Thorned Bark","Untrained Fists","Light Steps","Bulb Sprout","Lava Swirl",
    "Nightstalker","Unhoned Arcane Dust","Improved Execute","Discard (Earth DMG)",
    "Lesser Censer","Discard (Shadow DMG)","Discard (Nature DMG)","Toxic Infusion",
    "Discard (Lightning DMG)","Discard (Physical DMG)","Coppercleave Greataxe",
    "Verdigris Rapier","Gouge","Copperwind Katana","Copperbite Dagger","Copperpoint Spear",
    "Wooden Bow","Multi-Shot","Arm and a Leg","Crackling Fire","Earthen Wall","Ivybark",
    "Ice Spikes","Frozen Arsenal","Ice Clone","Ash Stomp","Scald","Disarm","Decaying Slice",
    "Cracked Arcane Crystal","Cracked Disease Crystal","Cracked Water Crystal",
    "Cracked Wind Crystal","Cracked Earth Crystal","Cracked Fire Crystal",
    "Cracked Frost Crystal","Cracked Holy Crystal","Cracked Lightning Crystal",
    "Cracked Nature Crystal","Cracked Physical Crystal","Cracked Shadow Crystal",
    "Harvest Scythe","Copper Glaive","Rusted Axe","Resurgence","Sanctified Resolve",
    "Shroom Colony","Lesser Cleanse","Winds of Misguidance","Arsenal",
    "Hymn Knowledge: Borealis","Basics of Defense","Sonic Boom","120dB","Padded Armor",
    "Tactician Training","Sympathetic Agony",
})

return ITEM_RARITY
